spring:
  application:
    name: periodic-table-microservice
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:5432/periodic-table
    username: periodic-table
    password: ${PT_PASSWORD}