name: Build Periodic Table frontend

on: workflow_dispatch

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 22

      - name: Run tests
        shell: bash
        run: |
          cd periodic-table-app
          npm ci
          npm run test
